In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, math, random

In [2]:
np.set_printoptions(linewidth=400)

In [3]:
data = pd.read_table('qws2.CSV', header=None, delimiter=',')

pd_data = data.iloc[1:, 0:9]
type(pd_data)

pandas.core.frame.DataFrame

In [4]:
item_size = pd_data.shape[0]

feature_dimension = pd_data.shape[1]

max_length = 10

epsilon = 1E-10

In [5]:
scores = np.exp(0.01 * np.random.randn(item_size) + 0.2) #mu=0.2, sigma=0.01 的正态分布
print('scores:', scores)

scores: [1.22291464 1.20263814 1.22131686 ... 1.22425014 1.21676213 1.21335845]


In [6]:
# item_data_x = np.linspace(-100,100,1000)
# item_data_y = np
# 0.01 * np.random.randn(item_size) + 0.2
# a = scores
# plt.figure(figsize=(10,5), dpi=200)
# plt.hist(a,100)# 画直方图
# plt.xlabel("区间")
# plt.ylabel("频数/频率")
# plt.title("随机生成 scores 频数/频率分布直方图")
# plt.show()

In [7]:
feature_vectors = pd_data.loc[:,:].values.astype(float)

print(type(feature_vectors))
print(feature_vectors)

<class 'numpy.ndarray'>
[[3.0275e+02 8.9000e+01 7.1000e+00 ... 8.0000e+01 1.8775e+02 3.2000e+01]
 [4.8200e+02 8.5000e+01 1.6000e+01 ... 8.4000e+01 1.0000e+00 2.0000e+00]
 [3.3214e+03 8.9000e+01 1.4000e+00 ... 8.0000e+01 2.6000e+00 9.6000e+01]
 ...
 [9.3930e+01 8.0000e+01 2.1000e+00 ... 8.2000e+01 3.7200e+00 6.0000e+01]
 [1.0675e+02 8.6000e+01 1.3000e+00 ... 8.7000e+01 1.2500e+00 9.6000e+01]
 [3.1650e+02 7.2000e+01 1.5900e+01 ... 8.7000e+01 5.5000e+00 8.0000e+00]]


In [8]:
feature_vectors = feature_vectors / np.linalg.norm(feature_vectors, axis=1, keepdims=True)
print('l2_norm_feature_vectors:', feature_vectors, sep='\n')

l2_norm_feature_vectors:
[[7.52615874e-01 2.21247937e-01 1.76501163e-02 ... 1.98874550e-01 4.66733709e-01 7.95498199e-02]
 [9.25520798e-01 1.63214249e-01 3.07226821e-02 ... 1.61294081e-01 1.92016763e-03 3.84033526e-03]
 [9.98003821e-01 2.67424399e-02 4.20667595e-04 ... 2.40381483e-02 7.81239819e-04 2.88457779e-02]
 ...
 [4.55423370e-01 3.87883207e-01 1.01819342e-02 ... 3.97580287e-01 1.80365691e-02 2.90912405e-01]
 [4.46778607e-01 3.59934053e-01 5.44086360e-03 ... 3.64119333e-01 5.23159961e-03 4.01786850e-01]
 [8.68583913e-01 1.97592549e-01 4.36350212e-02 ... 2.38757663e-01 1.50938753e-02 2.19547277e-02]]


In [9]:
similarities = np.dot(feature_vectors, feature_vectors.T)
print('similarities:', similarities, sep='\n')

similarities:
[[1.         0.86997638 0.77945642 ... 0.75845166 0.73581933 0.88588136]
 [0.86997638 1.         0.94487737 ... 0.73931327 0.71484563 0.98982433]
 [0.77945642 0.94487737 1.         ... 0.51003225 0.50232576 0.8947768 ]
 ...
 [0.75845166 0.73931327 0.51003225 ... 1.         0.9913373  0.81457884]
 [0.73581933 0.71484563 0.50232576 ... 0.9913373  1.         0.78706589]
 [0.88588136 0.98982433 0.8947768  ... 0.81457884 0.78706589 1.        ]]


In [10]:
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))
print('reshaped score:', scores.reshape((item_size, 1)) * scores.reshape((1, item_size)), sep='\n')

reshaped score:
[[1.4955202  1.47072378 1.49356626 ... 1.49715341 1.48799622 1.4838338 ]
 [1.47072378 1.44633849 1.46880223 ... 1.47232991 1.46332455 1.45923114]
 [1.49356626 1.46880223 1.49161486 ... 1.49519733 1.4860521  1.48189512]
 ...
 [1.49715341 1.47232991 1.49519733 ... 1.4987884  1.48962121 1.48545424]
 [1.48799622 1.46332455 1.4860521  ... 1.48962121 1.48051009 1.47636861]
 [1.4838338  1.45923114 1.48189512 ... 1.48545424 1.47636861 1.47223872]]


In [11]:
print('kernel_matrix:', kernel_matrix, sep='\n')

kernel_matrix:
[[1.4955202  1.27949495 1.16416981 ... 1.13551849 1.09489637 1.31450071]
 [1.27949495 1.44633849 1.38783799 ... 1.08851304 1.04605116 1.44438249]
 [1.16416981 1.38783799 1.49161486 ... 0.76259886 0.74648226 1.32596537]
 ...
 [1.13551849 1.08851304 0.76259886 ... 1.4987884  1.47671707 1.2100196 ]
 [1.09489637 1.04605116 0.74648226 ... 1.47671707 1.48051009 1.16199937]
 [1.31450071 1.44438249 1.32596537 ... 1.2100196  1.16199937 1.47223872]]


In [12]:
cis = np.zeros((max_length, item_size))
di2s = np.copy(np.diag(kernel_matrix))
selected_items = list()
selected_item = np.argmax(di2s)
selected_items.append(selected_item)

while len(selected_items) < max_length:
    k = len(selected_items) - 1
    ci_optimal = cis[:k, selected_item]
    di_optimal = math.sqrt(di2s[selected_item])
    elements = kernel_matrix[selected_item, :]
    eis = (elements - np.dot(ci_optimal, cis[:k, :])) / di_optimal
    cis[k, :] = eis
    di2s -= np.square(eis)
    di2s[selected_item] = -np.inf
    selected_item = np.argmax(di2s)
    if di2s[selected_item] < epsilon:
        break
    selected_items.append(selected_item)
    
print('scores:', scores)
print('selected_items_index:', selected_items)
print("selected_items_value:", scores[selected_items])


scores: [1.22291464 1.20263814 1.22131686 ... 1.22425014 1.21676213 1.21335845]
selected_items_index: [1886, 852, 1323, 1628, 1329, 950, 960, 639, 306]
selected_items_value: [1.26529398 1.24229485 1.2412679  1.22066163 1.21658216 1.20406151 1.23617242 1.23938555 1.24207665]


In [13]:
# 产生十个用户，随机挑选5-15个item，作为服务调用历史记录
# 并选择其中的一个服务作为约束条件，也就是参考服务

In [14]:
class User:
    call_num = np.random.randint(5, 15 + 1) # [low, hight + 1)
    call_history = np.random.choice(item_size, call_num, replace=False) # 从item_size中随机挑选call_num个数，不重复
    representative_item_index = call_history[np.random.randint(0, call_num)] # 随机选择一个item作为参考服务
    representative_item = None
    def __init__(self):
        print(f'call_num: {self.call_num}')
        print(f'call_history: {self.call_history}')
        print(f'representative_item: {self.representative_item_index}')
    def set_representative_item(self, item_value):
        self.representative_item = item_value
    def __str__(self):
        return f'call_num: {self.call_num} \ncall_history: {self.call_history} \nrepresentative_item_index: {self.representative_item_index} \nrepresentative_item: {self.representative_item}'


In [15]:
user = User()

call_num: 7
call_history: [1705 2491 2448 1204  163 2320 1139]
representative_item: 1139


In [16]:
user.set_representative_item(pd_data.iloc[user.representative_item_index].values.astype(float))

In [17]:
print(user)

call_num: 7 
call_history: [1705 2491 2448 1204  163 2320 1139] 
representative_item_index: 1139 
representative_item: [266.74  85.     4.4   86.    53.    89.    66.    82.44  10.  ]


In [18]:
similarities # (item_size, item_size)

array([[1.        , 0.86997638, 0.77945642, ..., 0.75845166, 0.73581933, 0.88588136],
       [0.86997638, 1.        , 0.94487737, ..., 0.73931327, 0.71484563, 0.98982433],
       [0.77945642, 0.94487737, 1.        , ..., 0.51003225, 0.50232576, 0.8947768 ],
       ...,
       [0.75845166, 0.73931327, 0.51003225, ..., 1.        , 0.9913373 , 0.81457884],
       [0.73581933, 0.71484563, 0.50232576, ..., 0.9913373 , 1.        , 0.78706589],
       [0.88588136, 0.98982433, 0.8947768 , ..., 0.81457884, 0.78706589, 1.        ]])

In [19]:
scores

array([1.22291464, 1.20263814, 1.22131686, ..., 1.22425014, 1.21676213, 1.21335845])

In [20]:
# 选择了一个参考服务，每个服务和参考服务的相似度就是该服务的分数
print(f"rep item index: {user.representative_item_index}")

rep item index: 1139


In [21]:
# 现在需要得到一个item——size维度的向量，表示每个服务与参考服务的相似度，作为得分
similarities_with_rep = similarities[user.representative_item_index]
similarities_with_rep[user.representative_item_index] # 参考服务与自身的相似度为1，丢失精度

1.0

In [22]:
scores = np.exp(0.01 * similarities_with_rep + 0.2)
scores
# 现在得到了用户隐含的对于每个item的评分，需要根据此来生成推荐列表

array([1.23329721, 1.23306351, 1.23172036, ..., 1.23146576, 1.23108702, 1.23322623])

In [23]:
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))
print('reshaped score:', scores.reshape((item_size, 1)) * scores.reshape((1, item_size)), sep='\n')

reshaped score:
[[1.52102201 1.52073379 1.51907728 ... 1.51876328 1.51829619 1.52093447]
 [1.52073379 1.52044562 1.51878943 ... 1.51847549 1.51800849 1.52064626]
 [1.51907728 1.51878943 1.51713504 ... 1.51682144 1.51635495 1.51898985]
 ...
 [1.51876328 1.51847549 1.51682144 ... 1.51650791 1.51604151 1.51867587]
 [1.51829619 1.51800849 1.51635495 ... 1.51604151 1.51557526 1.51820881]
 [1.52093447 1.52064626 1.51898985 ... 1.51867587 1.51820881 1.52084693]]


In [24]:
print('kernel_matrix:', kernel_matrix, sep='\n')

kernel_matrix:
[[1.52102201 1.32300247 1.18405455 ... 1.15190853 1.11719168 1.3473675 ]
 [1.32300247 1.52044562 1.43506975 ... 1.12262908 1.08514174 1.50517266]
 [1.18405455 1.43506975 1.51713504 ... 0.77362786 0.76170416 1.35915688]
 ...
 [1.15190853 1.12262908 0.77362786 ... 1.51650791 1.5029085  1.23708123]
 [1.11719168 1.08514174 0.76170416 ... 1.5029085  1.51557526 1.19493036]
 [1.3473675  1.50517266 1.35915688 ... 1.23708123 1.19493036 1.52084693]]


In [25]:
cis = np.zeros((max_length, item_size))
di2s = np.copy(np.diag(kernel_matrix))
selected_items = list()
selected_item = np.argmax(di2s)
selected_items.append(selected_item)

while len(selected_items) < max_length:
    k = len(selected_items) - 1
    ci_optimal = cis[:k, selected_item]
    di_optimal = math.sqrt(di2s[selected_item])
    elements = kernel_matrix[selected_item, :]
    eis = (elements - np.dot(ci_optimal, cis[:k, :])) / di_optimal
    cis[k, :] = eis
    di2s -= np.square(eis)
    di2s[selected_item] = -np.inf
    selected_item = np.argmax(di2s)
    if di2s[selected_item] < epsilon:
        break
    selected_items.append(selected_item)
    
print('scores:', scores)
print('selected_items_index:', selected_items)
print("selected_items_value:", scores[selected_items])

scores: [1.23329721 1.23306351 1.23172036 ... 1.23146576 1.23108702 1.23322623]
selected_items_index: [1139, 86, 1160, 1628, 1497, 1329, 2013, 950, 2461]
selected_items_value: [1.23367806 1.22890701 1.22954114 1.22953143 1.23137566 1.23196214 1.23133099 1.23122791 1.23017017]


In [26]:
# 如上得到的是user的推荐结果列表，该方法认为每个用户具有相同的多样性偏好
# 有的用户调用了3个不同的服务，有的用户调用了30个不同的服务，这两者的多样性偏好显然是不同的
# 我们需要根据用户的服务调用历史记录来计算用户的多样性偏好

In [27]:
# 如何评价推荐结果的准确度
# 如上我们选择出了推荐列表，计算他们与参考服务的相似度，然后计算推荐列表的平均相似度
print(f"user.representative_item_index: {user.representative_item_index}")
print(f"user.representative_item_value: {pd_data.iloc[user.representative_item_index].values.astype(float)}")
print(f"selected_items_index: {selected_items}")
print(f"selected_items_value:\n {pd_data.iloc[[index for index in selected_items],:].values.astype(float)}")


user.representative_item_index: 1139
user.representative_item_value: [266.74  85.     4.4   86.    53.    89.    66.    82.44  10.  ]
selected_items_index: [1139, 86, 1160, 1628, 1497, 1329, 2013, 950, 2461]
selected_items_value:
 [[2.6674e+02 8.5000e+01 4.4000e+00 8.6000e+01 5.3000e+01 8.9000e+01 6.6000e+01 8.2440e+01 1.0000e+01]
 [4.3000e+01 4.7000e+01 3.6000e+00 4.7000e+01 8.0000e+01 1.0000e+02 8.3000e+01 5.1700e+00 9.5000e+01]
 [4.1000e+01 9.7000e+01 4.3100e+01 9.9000e+01 7.3000e+01 1.0000e+02 8.4000e+01 1.0000e+00 5.0000e+00]
 [4.8350e+01 1.0000e+01 1.4900e+01 1.0000e+01 6.7000e+01 7.8000e+01 8.2000e+01 2.9200e+00 4.0000e+00]
 [1.2840e+03 9.4000e+01 8.2000e+00 9.8000e+01 6.7000e+01 1.0000e+02 8.2000e+01 1.2360e+03 5.0000e+00]
 [1.1767e+02 9.4000e+01 3.0000e+00 9.5000e+01 7.8000e+01 3.3000e+01 8.9000e+01 7.8400e+00 4.0000e+00]
 [1.3218e+02 1.3000e+01 9.0000e+00 1.4000e+01 3.3000e+01 7.8000e+01 5.9000e+01 6.5700e+00 9.6000e+01]
 [8.2000e+01 8.3000e+01 3.8700e+01 8.4000e+01 8.0000e+0

In [28]:
[index for index in selected_items]

[1139, 86, 1160, 1628, 1497, 1329, 2013, 950, 2461]