In [3]:
import numpy as np
import math

In [4]:
np.set_printoptions(linewidth=400)

In [5]:
item_size = 5

feature_dimension = 3

max_length = 5

epsilon = 1E-10

In [6]:
scores = np.exp(0.01 * np.random.randn(item_size) + 0.2)
print('scores:', scores)

scores: [1.21485832 1.22597906 1.21557559 1.22867031 1.2155553 ]


In [21]:
feature_vectors = np.random.randn(item_size, feature_dimension)
print('feature_vectors:', feature_vectors, sep='\n')
print(feature_vectors)

feature_vectors:
[[-0.37533169 -0.62744054  1.1600546 ]
 [-1.12609098  1.30291244 -0.08620326]
 [-0.33098967 -0.47158015  0.01218476]
 [-0.75957941 -0.14197233  0.84905149]
 [-0.46273288 -0.24686378 -0.76583849]]
[[-0.37533169 -0.62744054  1.1600546 ]
 [-1.12609098  1.30291244 -0.08620326]
 [-0.33098967 -0.47158015  0.01218476]
 [-0.75957941 -0.14197233  0.84905149]
 [-0.46273288 -0.24686378 -0.76583849]]


In [8]:
feature_vectors = feature_vectors / np.linalg.norm(feature_vectors, axis=1, keepdims=True)
print('l2_norm_feature_vectors:', feature_vectors, sep='\n')

l2_norm_feature_vectors:
[[-0.2827005  -0.95909892 -0.01448061]
 [-0.31479547 -0.37614362 -0.87144695]
 [ 0.88255676 -0.46664144 -0.05778697]
 [ 0.76164137 -0.47612993  0.43954831]
 [ 0.62716036 -0.53082275 -0.56999744]]


In [9]:
similarities = np.dot(feature_vectors, feature_vectors.T)
print('similarities:', similarities, sep='\n')

similarities:
[[ 1.          0.46237087  0.19889286  0.23497438  0.34006689]
 [ 0.46237087  1.         -0.0519424  -0.44371106  0.49896088]
 [ 0.19889286 -0.0519424   1.          0.86897353  0.83414693]
 [ 0.23497438 -0.44371106  0.86897353  1.          0.47987046]
 [ 0.34006689  0.49896088  0.83414693  0.47987046  1.        ]]


In [10]:
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))
print('reshaeped score:', scores.reshape((item_size, 1)) * scores.reshape((1, item_size)), sep='\n')

reshaeped score:
[[1.47588074 1.48939087 1.47675212 1.49266034 1.47672747]
 [1.48939087 1.50302467 1.49027023 1.50632407 1.49024535]
 [1.47675212 1.49027023 1.47762402 1.49354163 1.47759936]
 [1.49266034 1.50632407 1.49354163 1.50963072 1.4935167 ]
 [1.47672747 1.49024535 1.47759936 1.4935167  1.47757469]]


In [11]:
print('kernel_matrix:', kernel_matrix, sep='\n')

kernel_matrix:
[[ 1.47588074  0.68865094  0.29371545  0.35073694  0.50218612]
 [ 0.68865094  1.50302467 -0.07740821 -0.66837264  0.74357413]
 [ 0.29371545 -0.07740821  1.47762402  1.29784814  1.23253497]
 [ 0.35073694 -0.66837264  1.29784814  1.50963072  0.71669454]
 [ 0.50218612  0.74357413  1.23253497  0.71669454  1.47757469]]


In [12]:
cis = np.zeros((max_length, item_size))

In [13]:
di2s = np.copy(np.diag(kernel_matrix))

In [14]:
selected_items = list()

In [15]:
selected_item = np.argmax(di2s)

In [16]:
selected_items.append(selected_item)

In [17]:
while len(selected_items) < max_length:
    k = len(selected_items) - 1
    
    
    ci_optimal = cis[:k, selected_item]
    
    
    di_optimal = math.sqrt(di2s[selected_item])
    
    
    elements = kernel_matrix[selected_item, :]
    
    
    eis = (elements - np.dot(ci_optimal, cis[:k, :])) / di_optimal
    
    
    cis[k, :] = eis
    
    
    di2s -= np.square(eis)
    
    
    di2s[selected_item] = -np.inf
    
    
    selected_item = np.argmax(di2s)
    
    
    if di2s[selected_item] < epsilon:
        break
        
        
    selected_items.append(selected_item)

In [18]:
print('scores:', scores)
print('selected_items_index:', selected_items)
print("selected_items_value:", scores[selected_items])

scores: [1.21485832 1.22597906 1.21557559 1.22867031 1.2155553 ]
selected_items_index: [3, 0, 4]
selected_items_value: [1.22867031 1.21485832 1.2155553 ]
