In [1]:
import numpy as np
import math

In [2]:
np.set_printoptions(linewidth=400)

In [3]:
item_size = 5

feature_dimension = 3

max_length = 5

epsilon = 1E-10

In [4]:
scores = np.exp(0.01 * np.random.randn(item_size) + 0.2)
print('scores:', scores)

scores: [1.20850767 1.20791515 1.24230528 1.22904142 1.22920874]


In [5]:
feature_vectors = np.random.randn(item_size, feature_dimension)
print('feature_vectors:', feature_vectors, sep='\n')
print(feature_vectors)

feature_vectors:
[[ 0.43782717  2.02171097  0.45931729]
 [ 0.07076138 -0.98189445 -0.47485367]
 [ 0.24727843 -1.89269481 -1.04290832]
 [ 1.55632871 -0.98386339 -1.49565539]
 [-0.11288269  0.73328155  0.1642687 ]]
[[ 0.43782717  2.02171097  0.45931729]
 [ 0.07076138 -0.98189445 -0.47485367]
 [ 0.24727843 -1.89269481 -1.04290832]
 [ 1.55632871 -0.98386339 -1.49565539]
 [-0.11288269  0.73328155  0.1642687 ]]


In [6]:
feature_vectors = feature_vectors / np.linalg.norm(feature_vectors, axis=1, keepdims=True)
print('l2_norm_feature_vectors:', feature_vectors, sep='\n')

l2_norm_feature_vectors:
[[ 0.20662387  0.9541065   0.21676571]
 [ 0.06474157 -0.89836278 -0.43445695]
 [ 0.11368555 -0.87016101 -0.47947411]
 [ 0.65608152 -0.41475466 -0.63050425]
 [-0.14855191  0.96498738  0.21617511]]


In [7]:
similarities = np.dot(feature_vectors, feature_vectors.T)
print('similarities:', similarities, sep='\n')

similarities:
[[ 1.         -0.93793198 -0.91066966 -0.39682971  0.93686571]
 [-0.93793198  1.          0.9973913   0.68900285 -0.97044502]
 [-0.91066966  0.9973913   1.          0.73780078 -0.96023297]
 [-0.39682971  0.68900285  0.73780078  1.         -0.63399451]
 [ 0.93686571 -0.97044502 -0.96023297 -0.63399451  1.        ]]


In [8]:
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))
print('reshaeped score:', scores.reshape((item_size, 1)) * scores.reshape((1, item_size)), sep='\n')

reshaeped score:
[[1.46049079 1.45977473 1.50133547 1.48530599 1.48550819]
 [1.45977473 1.45905902 1.50059938 1.48457776 1.48477986]
 [1.50133547 1.50059938 1.54332242 1.52684465 1.52705251]
 [1.48530599 1.48457776 1.52684465 1.51054281 1.51074845]
 [1.48550819 1.48477986 1.52705251 1.51074845 1.51095412]]


In [9]:
print('kernel_matrix:', kernel_matrix, sep='\n')

kernel_matrix:
[[ 1.46049079 -1.3691694  -1.36722066 -0.58941355  1.39172168]
 [-1.3691694   1.45905902  1.49668477  1.02287831 -1.44089722]
 [-1.36722066  1.49668477  1.54332242  1.12650718 -1.46632616]
 [-0.58941355  1.02287831  1.12650718  1.51054281 -0.95780622]
 [ 1.39172168 -1.44089722 -1.46632616 -0.95780622  1.51095412]]


In [10]:
cis = np.zeros((max_length, item_size))

In [11]:
di2s = np.copy(np.diag(kernel_matrix))

In [12]:
selected_items = list()

In [13]:
selected_item = np.argmax(di2s)

In [14]:
selected_items.append(selected_item)

In [15]:
while len(selected_items) < max_length:
    k = len(selected_items) - 1
    
    
    ci_optimal = cis[:k, selected_item]
    
    
    di_optimal = math.sqrt(di2s[selected_item])
    
    
    elements = kernel_matrix[selected_item, :]
    
    
    eis = (elements - np.dot(ci_optimal, cis[:k, :])) / di_optimal
    
    
    cis[k, :] = eis
    
    
    di2s -= np.square(eis)
    
    
    di2s[selected_item] = -np.inf
    
    
    selected_item = np.argmax(di2s)
    
    
    if di2s[selected_item] < epsilon:
        break
        
        
    selected_items.append(selected_item)

In [16]:
print('scores:', scores)
print('selected_items_index:', selected_items)
print("selected_items_value:", scores[selected_items])

scores: [1.20850767 1.20791515 1.24230528 1.22904142 1.22920874]
selected_items_index: [2, 3, 4]
selected_items_value: [1.24230528 1.22904142 1.22920874]
