In [4]:
import numpy as np
import math

In [5]:
np.set_printoptions(linewidth=400)

In [6]:
item_size = 5

feature_dimension = 3

max_length = 5

epsilon = 1E-10

In [7]:
scores = np.exp(0.01 * np.random.randn(item_size) + 0.2)
print('scores:', scores)

scores: [1.21297624 1.22586152 1.21057362 1.21677457 1.22013304]


In [8]:
feature_vectors = np.random.randn(item_size, feature_dimension)
print('feature_vectors:', feature_vectors, sep='\n')

feature_vectors:
[[-0.17174287 -0.99873789 -0.05258756]
 [-1.70913402  0.96420233 -1.28747995]
 [-0.53881915  0.95417399 -0.02756083]
 [-1.06347204  0.16266527 -1.94222414]
 [-0.55641947 -0.03230687 -0.84759519]]


In [9]:
feature_vectors = feature_vectors / np.linalg.norm(feature_vectors, axis=1, keepdims=True)
print('l2_norm_feature_vectors:', feature_vectors, sep='\n')

l2_norm_feature_vectors:
[[-0.16924477 -0.98421066 -0.05182264]
 [-0.72821934  0.41082254 -0.54856306]
 [-0.49155832  0.87048161 -0.02514342]
 [-0.47897988  0.07326322 -0.87476327]
 [-0.54850568 -0.03184738 -0.8355401 ]]


In [10]:
similarities = np.dot(feature_vectors, feature_vectors.T)
print('similarities:', similarities, sep='\n')

similarities:
[[ 1.         -0.25266062 -0.7722406   0.05429094  0.16747615]
 [-0.25266062  1.          0.72936849  0.85876341  0.84469526]
 [-0.7722406   0.72936849  1.          0.32121537  0.26290831]
 [ 0.05429094  0.85876341  0.32121537  1.          0.99128973]
 [ 0.16747615  0.84469526  0.26290831  0.99128973  1.        ]]


In [11]:
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))
print('reshaeped score:', scores.reshape((item_size, 1)) * scores.reshape((1, item_size)), sep='\n')

reshaeped score:
[[1.47131136 1.4869409  1.46839703 1.47591865 1.47999239]
 [1.4869409  1.50273646 1.48399561 1.49159713 1.49571415]
 [1.46839703 1.48399561 1.46548848 1.4729952  1.47706087]
 [1.47591865 1.49159713 1.4729952  1.48054036 1.48462686]
 [1.47999239 1.49571415 1.47706087 1.48462686 1.48872464]]


In [12]:
print('kernel_matrix:', kernel_matrix, sep='\n')

kernel_matrix:
[[ 1.47131136 -0.37569141 -1.13395581  0.08012901  0.24786343]
 [-0.37569141  1.50273646  1.08237964  1.28092904  1.26342265]
 [-1.13395581  1.08237964  1.46548848  0.4731487   0.38833158]
 [ 0.08012901  1.28092904  0.4731487   1.48054036  1.47169537]
 [ 0.24786343  1.26342265  0.38833158  1.47169537  1.48872464]]


In [13]:
cis = np.zeros((max_length, item_size))

In [14]:
di2s = np.copy(np.diag(kernel_matrix))

In [15]:
selected_items = list()

In [16]:
selected_item = np.argmax(di2s)

In [17]:
selected_items.append(selected_item)

In [18]:
while len(selected_items) < max_length:
    k = len(selected_items) - 1
    
    
    ci_optimal = cis[:k, selected_item]
    
    
    di_optimal = math.sqrt(di2s[selected_item])
    
    
    elements = kernel_matrix[selected_item, :]
    
    
    eis = (elements - np.dot(ci_optimal, cis[:k, :])) / di_optimal
    
    
    cis[k, :] = eis
    
    
    di2s -= np.square(eis)
    
    
    di2s[selected_item] = -np.inf
    
    
    selected_item = np.argmax(di2s)
    
    
    if di2s[selected_item] < epsilon:
        break
        
        
    selected_items.append(selected_item)

In [19]:
print('scores:', scores)
print('selected_items_index:', selected_items)
print("selected_items_value:", scores[selected_items])

scores: [1.21297624 1.22586152 1.21057362 1.21677457 1.22013304]
selected_items_index: [1, 0, 3]
selected_items_value: [1.22586152 1.21297624 1.21677457]
