## 数组的创建和访问

In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5]

In [3]:
list

[1, 2, 3, 4, 5]

In [4]:
array_1 = np.array(list)

In [5]:
array_1

array([1, 2, 3, 4, 5])

In [6]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
array_2 = np.array([list1, list2])
array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
# 返回数组的形状, 2行5列
array_2.shape

(2, 5)

In [9]:
# 返回数组的元素个数
array_2.size

10

In [10]:
# 返回数组的元素类型
array_2.dtype

dtype('int64')

In [12]:
# 指定范围和步长
array_3 = np.arange(1, 10, 2)
array_3

array([1, 3, 5, 7, 9])

In [14]:
# 返回全 0 数组
array_4 = np.zeros(5)
array_4

array([0., 0., 0., 0., 0.])

In [16]:
# 返回 2*3 的全 0 数组
array_5 = np.zeros((2, 3))
array_5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# 返回单位阵
array_6 = np.eye(5)
array_6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# 数组访问
a = np.arange(1, 10)
a[1:5]

array([2, 3, 4, 5])

In [22]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b[1][0]

4

In [24]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# 指定范围访问
c[:2, 1:]

array([[2, 3],
       [5, 6]])

### 随机创建数组

In [26]:
# 随机创建数组，符合标准正态分布
np.random.rand(10)

array([0.08473853, 0.31951061, 0.06791561, 0.53262922, 0.50807889,
       0.07955702, 0.02768437, 0.11469169, 0.80559945, 0.93883897])

In [29]:
# 随机创建数组，指定形状
np.random.randint(10, size=(2, 3))

array([[2, 9, 5],
       [4, 3, 3]])

In [30]:
# 一维数组 reshape
np.random.randint(10, size=10).reshape(5, 2)

array([[8, 7],
       [5, 6],
       [9, 7],
       [3, 4],
       [4, 8]])

### 数组运算

In [37]:
a = np.random.randint(10, size=20).reshape(4, 5)
a


array([[2, 8, 8, 1, 7],
       [4, 6, 6, 9, 1],
       [9, 0, 2, 6, 5],
       [0, 5, 0, 8, 6]])

In [38]:
b = np.random.randint(10, size=20).reshape(4, 5)
b

array([[2, 7, 9, 4, 2],
       [9, 0, 4, 9, 2],
       [1, 4, 5, 3, 4],
       [8, 1, 5, 4, 2]])

In [39]:
# 数组加法
a + b

array([[ 4, 15, 17,  5,  9],
       [13,  6, 10, 18,  3],
       [10,  4,  7,  9,  9],
       [ 8,  6,  5, 12,  8]])

In [40]:
# 数组减法
a - b

array([[ 0,  1, -1, -3,  5],
       [-5,  6,  2,  0, -1],
       [ 8, -4, -3,  3,  1],
       [-8,  4, -5,  4,  4]])

In [41]:
# 数组乘法，点乘
a * b

array([[ 4, 56, 72,  4, 14],
       [36,  0, 24, 81,  2],
       [ 9,  0, 10, 18, 20],
       [ 0,  5,  0, 32, 12]])

In [42]:
# 数组除法，注意 /zero 错误
a / b

/tmp/ipykernel_295172/373119961.py:2: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[1.        , 1.14285714, 0.88888889, 0.25      , 3.5       ],
       [0.44444444,        inf, 1.5       , 1.        , 0.5       ],
       [9.        , 0.        , 0.4       , 2.        , 1.25      ],
       [0.        , 5.        , 0.        , 2.        , 3.        ]])

In [43]:
# 矩阵
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [45]:
# 可以将数组转换为矩阵
a

array([[2, 8, 8, 1, 7],
       [4, 6, 6, 9, 1],
       [9, 0, 2, 6, 5],
       [0, 5, 0, 8, 6]])

In [46]:
np.mat(a)

matrix([[2, 8, 8, 1, 7],
        [4, 6, 6, 9, 1],
        [9, 0, 2, 6, 5],
        [0, 5, 0, 8, 6]])

### 矩阵运算

In [48]:
A = np.mat(a)
A

matrix([[2, 8, 8, 1, 7],
        [4, 6, 6, 9, 1],
        [9, 0, 2, 6, 5],
        [0, 5, 0, 8, 6]])

In [49]:
B = np.mat(b)
B

matrix([[2, 7, 9, 4, 2],
        [9, 0, 4, 9, 2],
        [1, 4, 5, 3, 4],
        [8, 1, 5, 4, 2]])

In [50]:
A + B

matrix([[ 4, 15, 17,  5,  9],
        [13,  6, 10, 18,  3],
        [10,  4,  7,  9,  9],
        [ 8,  6,  5, 12,  8]])

In [51]:
A - B

matrix([[ 0,  1, -1, -3,  5],
        [-5,  6,  2,  0, -1],
        [ 8, -4, -3,  3,  1],
        [-8,  4, -5,  4,  4]])

In [53]:
# 矩阵乘法，需要满足 n x m × m x n
A = np.mat(np.random.randint(10, size=20).reshape(4, 5))
A

matrix([[4, 6, 1, 0, 2],
        [3, 3, 7, 8, 0],
        [5, 7, 8, 7, 9],
        [7, 1, 6, 4, 1]])

In [54]:
B = np.mat(np.random.randint(10, size=20).reshape(5, 4))
B

matrix([[2, 4, 4, 6],
        [3, 2, 5, 8],
        [3, 7, 0, 4],
        [3, 0, 2, 7],
        [0, 7, 6, 4]])

In [55]:
A * B

matrix([[ 29,  49,  58,  84],
        [ 60,  67,  43, 126],
        [ 76, 153, 123, 203],
        [ 47,  79,  47, 106]])

### Array 的基操

In [61]:
a = np.random.randint(10, size=20).reshape(4, 5)
a

array([[3, 4, 7, 8, 3],
       [8, 6, 5, 3, 9],
       [4, 9, 2, 9, 5],
       [3, 4, 7, 9, 2]])

In [62]:
# 查询 array 中的唯一值
np.unique(a)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# 求列和
sum(a)

array([18, 23, 21, 29, 19])

In [65]:
# 求行和
sum(a[0])

25

In [66]:
# 求列和
sum(a[:, 0])

18

In [68]:
# 求最大值
a.max()

9

In [69]:
# 求行最大值
max(a[0])

8

In [70]:
# 求列最大值
max(a[:, 0])

8

### Array 的输入和输出

In [71]:
import pickle as pk

In [72]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# 写文件
f = open('x.pkl', 'wb')
pk.dump(x, f)

In [76]:
# 读文件
f = open('x.pkl', 'rb')
pk.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# numpy 序列化到文件
np.save('x.npy', x)

In [78]:
# numpy 读取文件
np.load('x.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# 多个文件
x = np.arange(10)
y = np.arange(20)
np.savez('x_y.npz', x=x, y=y)

In [80]:
# 读取多个文件
z = np.load('x_y.npz')

In [81]:
z['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
z['y']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])